import { localFont } from "next/font/local";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

const clashDisplay = localFont({
  src: [
    {path: "../public/fonts/clash_display/ClashDisplay-Extralight.otf", weight: "200", style: "normal"},
    {path: "../public/fonts/clash_display/ClashDisplay-Light.otf", weight: "300", style: "normal"},
    {path: "../public/fonts/clash_display/ClashDisplay-Regular.otf", weight: "400", style: "normal"},
    {path: "../public/fonts/clash_display/ClashDisplay-Medium.otf", weight: "500", style: "normal"},
    {path: "../public/fonts/clash_display/ClashDisplay-Semibold.otf", weight: "600", style: "normal"},
    {path: "../public/fonts/clash_display/ClashDisplay-Bold.otf", weight: "700", style: "normal"},
  ],
  variable: "--font-clash-display",
  display: "swap",
});

const clashGrotesk = localFont({
  src: [
    {path: "../public/fonts/clash_grotesk/ClashGrotesk-Extralight.otf", weight: "200", style: "normal"},
    {path: "../public/fonts/clash_grotesk/ClashGrotesk-Light.otf", weight: "300", style: "normal"},
    {path: "../public/fonts/clash_grotesk/ClashGrotesk-Regular.otf", weight: "400", style: "normal"},
    {path: "../public/fonts/clash_grotesk/ClashGrotesk-Medium.otf", weight: "500", style: "normal"},
    {path: "../public/fonts/clash_grotesk/ClashGrotesk-Semibold.otf", weight: "600", style: "normal"},
    {path: "../public/fonts/clash_grotesk/ClashGrotesk-Bold.otf", weight: "700", style: "normal"},
  ],
  variable: "--font-clash-grotesk",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  weight: ['300', '400', '500'],
  variable: "--font-jetbrains-mono",
  display: 'swap',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${clashDisplay.variable} ${clashGrotesk.variable} ${jetbrainsMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
